--Create Intwenty System tables
CREATE TABLE sysmodel_SystemItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,Title TEXT NOT NULL ,TitleLocalizationKey TEXT NULL ,Description TEXT NULL ,MetaCode TEXT NOT NULL ,DbPrefix TEXT NOT NULL )
CREATE TABLE sysmodel_ApplicationItem (SystemMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,Id INTEGER NOT NULL ,Title TEXT NOT NULL ,TitleLocalizationKey TEXT NULL ,Description TEXT NULL ,DbName TEXT NOT NULL ,DataMode INTEGER NULL ,UseVersioning INTEGER NULL ,TenantIsolationLevel INTEGER NULL ,TenantIsolationMethod INTEGER NULL , PRIMARY KEY (Id))
CREATE TABLE sysmodel_DatabaseItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,SystemMetaCode TEXT NOT NULL ,AppMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,MetaType TEXT NOT NULL ,Description TEXT NULL ,ParentMetaCode TEXT NOT NULL ,DbName TEXT NULL ,DataType TEXT NULL ,Properties TEXT NULL )
CREATE TABLE sysmodel_ViewItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,SystemMetaCode TEXT NOT NULL ,AppMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,MetaType TEXT NOT NULL ,Title TEXT NULL ,TitleLocalizationKey TEXT NULL ,Description TEXT NULL ,DescriptionLocalizationKey TEXT NULL ,Path TEXT NOT NULL ,FilePath TEXT NULL ,IsPrimary INTEGER NULL ,IsPublic INTEGER NULL ,Properties TEXT NULL )
CREATE TABLE sysmodel_UserInterfaceItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,SystemMetaCode TEXT NOT NULL ,AppMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,MetaType TEXT NOT NULL ,ViewMetaCode TEXT NOT NULL ,DataTableMetaCode TEXT NULL )
CREATE TABLE sysmodel_FunctionItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,SystemMetaCode TEXT NOT NULL ,AppMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,MetaType TEXT NOT NULL ,OwnerMetaType TEXT NOT NULL ,OwnerMetaCode TEXT NOT NULL ,Title TEXT NOT NULL ,TitleLocalizationKey TEXT NULL ,IsModalAction INTEGER NULL ,ActionMetaCode TEXT NULL ,ActionMetaType TEXT NULL ,ActionPath TEXT NULL ,Properties TEXT NULL )
CREATE TABLE sysmodel_UserInterfaceStructureItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,SystemMetaCode TEXT NOT NULL ,AppMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,MetaType TEXT NOT NULL ,Title TEXT NULL ,TitleLocalizationKey TEXT NULL ,Description TEXT NULL ,UserInterfaceMetaCode TEXT NOT NULL ,ParentMetaCode TEXT NOT NULL ,DataTableMetaCode TEXT NULL ,DataColumn1MetaCode TEXT NULL ,DataColumn2MetaCode TEXT NULL ,ColumnOrder INTEGER NULL ,RowOrder INTEGER NULL ,Domain TEXT NULL ,Properties TEXT NULL ,RawHTML TEXT NULL )
CREATE TABLE sysmodel_ValueDomainItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,DomainName TEXT NULL ,Code TEXT NULL ,Value TEXT NULL ,Properties TEXT NULL ,ValueLocalizationKey TEXT NULL )
CREATE TABLE sysmodel_EndpointItem (Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,SystemMetaCode TEXT NOT NULL ,AppMetaCode TEXT NOT NULL ,MetaCode TEXT NOT NULL ,MetaType TEXT NOT NULL ,ParentMetaCode TEXT NOT NULL ,Title TEXT NULL ,Path TEXT NULL ,Description TEXT NULL ,DataMetaCode TEXT NULL ,OrderNo INTEGER NULL ,Properties TEXT NULL )


-- Systems
INSERT INTO sysmodel_SystemItem (Title,MetaCode,DbPrefix)  VALUES ('Default','INTWENTYDEFAULTSYS','def')
INSERT INTO sysmodel_SystemItem (Title,MetaCode,DbPrefix)  VALUES ('WMS','WAREHOUSE','wms')
INSERT INTO sysmodel_SystemItem (Title,MetaCode,DbPrefix)  VALUES ('The blog engine','BLOG','blog')


-- Applications
INSERT INTO sysmodel_ApplicationItem (SystemMetaCode,MetaCode,Id,Title,TitleLocalizationKey,Description,DbName,DataMode,UseVersioning,TenantIsolationLevel,TenantIsolationMethod)  VALUES ('WAREHOUSE','CUSTOMER',10,'Customer','CUSTOMER','An app for managing customers','wms_Customer',0,0,0,0)
INSERT INTO sysmodel_ApplicationItem (SystemMetaCode,MetaCode,Id,Title,TitleLocalizationKey,Description,DbName,DataMode,UseVersioning,TenantIsolationLevel,TenantIsolationMethod)  VALUES ('WAREHOUSE','ITEM',20,'Item','ITEM','An app for managing items','wms_Item',0,0,0,0)
INSERT INTO sysmodel_ApplicationItem (SystemMetaCode,MetaCode,Id,Title,TitleLocalizationKey,Description,DbName,DataMode,UseVersioning,TenantIsolationLevel,TenantIsolationMethod)  VALUES ('WAREHOUSE','SALESORDER',30,'Sales Order','SALESORDER','An app for managing sales orders','wms_SalesHeader',0,0,2,2)
INSERT INTO sysmodel_ApplicationItem (SystemMetaCode,MetaCode,Id,Title,TitleLocalizationKey,Description,DbName,DataMode,UseVersioning,TenantIsolationLevel,TenantIsolationMethod)  VALUES ('WAREHOUSE','VENDOR',40,'Vendor','VENDOR','An app for managing vendors','wms_Vendor',0,0,0,0)
INSERT INTO sysmodel_ApplicationItem (SystemMetaCode,MetaCode,Id,Title,TitleLocalizationKey,Description,DbName,DataMode,UseVersioning,TenantIsolationLevel,TenantIsolationMethod)  VALUES ('BLOG','BLOGAPP',50,'The blog','','An app for blogging','blog_Blog',0,0,0,0)


-- Application: Customer
-- Database
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMERID','DATACOLUMN','ROOT','CustomerId','STRING','DEFVALUE=AUTO#DEFVALUE_START=1000#DEFVALUE_PREFIX=CUST#DEFVALUE_SEED=100#UNIQUE=TRUE#MANDATORY=TRUE')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMERNAME','DATACOLUMN','ROOT','CustomerName','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMERPHONE','DATACOLUMN','ROOT','CustomerPhone','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMEREMAIL','DATACOLUMN','ROOT','CustomerEmail','STRING','MANDATORY=TRUE')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMERSTATUS','DATACOLUMN','ROOT','CustomerStatus','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMERTAGS','DATACOLUMN','ROOT','CustomerTags','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','CUSTOMER','CUSTOMERTAGSTEXT','DATACOLUMN','ROOT','CustomerTagsText','TEXT')

-- Views
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','CUSTOMER','LV_CUSTOMER1','UIVIEW','Customer List','CUSTOMERLIST','Customers/List/{requestinfo}',1,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','CUSTOMER','INPUT_CUSTOMER1','UIVIEW','Create Customer','CUST_ADD','Customers/Create/{requestinfo}',0,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','CUSTOMER','INPUT_CUSTOMER2','UIVIEW','Edit Customer','CUST_EDIT','Customers/Edit/{id}/{requestinfo}',0,0)

-- Userinterface
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','CUSTOMER','CUST_INPUTVIEW','INPUTINTERFACE','INPUT_CUSTOMER1','CUSTOMER')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','CUSTOMER','CUST_INPUTVIEW','INPUTINTERFACE','INPUT_CUSTOMER2','CUSTOMER')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','CUSTOMER','CUST_LISTVIEW','LISTINTERFACE','LV_CUSTOMER1','CUSTOMER')

-- UI Components
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','CUSTOMER','MAINSECTION','SECTION','','CUST_INPUTVIEW','ROOT',1,1,'COLLAPSIBLE=FALSE#STARTEXPANDED=FALSE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','CUSTPNL1','PANEL','Basics','CUSTOMERBASIC','CUST_INPUTVIEW','MAINSECTION',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','CUSTOMER','TB_CUSTID','TEXTBOX','Customer ID','CUSTOMERID','CUST_INPUTVIEW','CUSTPNL1','CUSTOMERID',1,1,'READONLY=TRUE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','TB_CUSTNAME','TEXTBOX','Customer Name','CUSTOMERNAME','CUST_INPUTVIEW','CUSTPNL1','CUSTOMERNAME',1,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain,Properties)  VALUES ('WAREHOUSE','CUSTOMER','MS_TAGS','SEARCHBOX','Tags','MS_TAGS','CUST_INPUTVIEW','CUSTPNL1','CUSTOMERTAGS','CUSTOMERTAGSTEXT',1,3,'VALUEDOMAIN.CUSTOMERTAGS','MULTISELECT=TRUE#ALLOWCREATE=TRUE#USESEARCH=TRUE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','CUSTPNL2','PANEL','Contact','CUSTOMERCONTACT','CUST_INPUTVIEW','MAINSECTION',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','TBCUSTMAIL','EMAILBOX','Email','CUSTOMEREMAIL','CUST_INPUTVIEW','CUSTPNL2','CUSTOMEREMAIL',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','TBCUSTPHONE','NUMBOX','Phone','CUSTOMERPHONE','CUST_INPUTVIEW','CUSTPNL2','CUSTOMERPHONE',2,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','CUSTOMER','TBCUSTSTAT','TEXTBOX','Status','','CUST_INPUTVIEW','CUSTPNL2','CUSTOMERSTATUS',2,3,'READONLY=TRUE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','CUST_LISTVIEW','TABLE','Customer List','CUSTOMERLIST','CUST_LISTVIEW','ROOT',0,0)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','LV_ID','TABLETEXTCOLUMN','ID','CUST_LISTVIEW','CUST_LISTVIEW','ID',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','LV_CUSTID','TABLETEXTCOLUMN','Customer ID','CUSTOMERID','CUST_LISTVIEW','CUST_LISTVIEW','CUSTOMERID',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','CUSTOMER','LV_CUSTNAME','TABLETEXTCOLUMN','Customer Name','CUSTOMERNAME','CUST_LISTVIEW','CUST_LISTVIEW','CUSTOMERNAME',3,1)

-- Functions
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_CREATE','CREATE','LISTINTERFACE','CUST_LISTVIEW','Create',0,'INPUT_CUSTOMER1','UIVIEW','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_EDIT','EDIT','LISTINTERFACE','CUST_LISTVIEW','Edit',0,'INPUT_CUSTOMER2','UIVIEW','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_DELETE','DELETE','LISTINTERFACE','CUST_LISTVIEW','Delete',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_FILTER','FILTER','LISTINTERFACE','CUST_LISTVIEW','Filter',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_PAGING','PAGING','LISTINTERFACE','CUST_LISTVIEW','Paging',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_SAVE','SAVE','UIVIEW','INPUT_CUSTOMER1','Save',0,'','AFTERSAVEACTION=GOTOVIEW#GOTOVIEWPATH=Customers/List/{requestinfo}')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_BACK','NAVIGATE','UIVIEW','INPUT_CUSTOMER1','Back to list',0,'LV_CUSTOMER1','UIVIEW','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_SAVE1','SAVE','UIVIEW','INPUT_CUSTOMER2','Save',0,'','AFTERSAVEACTION=REFRESH')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','CUSTOMER','CUST_FUNC_BACK1','NAVIGATE','UIVIEW','INPUT_CUSTOMER2','Back to list',0,'LV_CUSTOMER1','UIVIEW','')


-- Application: Item
-- Database
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','ITEM','ITEMID','DATACOLUMN','ROOT','ItemId','STRING','DEFVALUE=AUTO#DEFVALUE_START=1000#DEFVALUE_PREFIX=ITEM#DEFVALUE_SEED=100#UNIQUE=TRUE#MANDATORY=TRUE')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','NAME','DATACOLUMN','ROOT','ItemName','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','CATCODE','DATACOLUMN','ROOT','ItemCategoryCode','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','CATVALUE','DATACOLUMN','ROOT','ItemCategoryValue','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','MODIFIED','DATACOLUMN','ROOT','Modified','DATETIME')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','ACTIVE','DATACOLUMN','ROOT','Active','BOOLEAN')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','PURCHASEPRICE','DATACOLUMN','ROOT','PurchasePrice','2DECIMAL')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','SALESPRICE','DATACOLUMN','ROOT','SalesPrice','2DECIMAL')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','VENDORCODE','DATACOLUMN','ROOT','VendorCode','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','ITEM','VENDORTXT','DATACOLUMN','ROOT','VendorName','STRING')

-- Views
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','ITEM','ITEM_LISTVIEW','UIVIEW','Item List','ITEMLIST','Items/List',1,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','ITEM','ITEM_CREATE_VIEW','UIVIEW','Create Item','','Items/Create',0,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','ITEM','ITEM_EDIT_VIEW','UIVIEW','Edit Item','','Items/Edit/{id}',0,0)

-- Userinterface
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','ITEM','ITEMINPUTUI','INPUTINTERFACE','ITEM_CREATE_VIEW','ITEM')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','ITEM','ITEMINPUTUI','INPUTINTERFACE','ITEM_EDIT_VIEW','ITEM')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','ITEM','ITEMLISTUI','LISTINTERFACE','ITEM_LISTVIEW','ITEM')

-- UI Components
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','ITEM','MAINSECTION','SECTION','Basics','ITEMINPUTUI','ROOT',1,1,'COLLAPSIBLE=FALSE#STARTEXPANDED=FALSE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','ITMPNL_A','PANEL','Basics','ITEMINPUTUI','MAINSECTION',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','ITEM','TB_ITID','TEXTBOX','Item ID','ITEMINPUTUI','ITMPNL_A','ITEMID',1,1,'READONLY=TRUE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','TB_ITNAME','TEXTBOX','Item Name','ITEMINPUTUI','ITMPNL_A','NAME',1,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','DP_MOD','DATEPICKER','Modified Date','ITEMINPUTUI','ITMPNL_A','MODIFIED',1,3)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','CB_ACTIVE','CHECKBOX','Is Active','ITEMINPUTUI','ITMPNL_A','ACTIVE',1,4)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','ITMPNL_B','PANEL','Basics','ITEMINPUTUI','MAINSECTION',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Domain)  VALUES ('WAREHOUSE','ITEM','CB_CATEGORY','COMBOBOX','Category','ITEMINPUTUI','ITMPNL_B','CATCODE',2,1,'VALUEDOMAIN.ITEMCATEGORY')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','NUMBOX_PURCHPRICE','NUMBOX','Purchase Price','ITEMINPUTUI','ITMPNL_B','PURCHASEPRICE',2,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','NUMBOX_SALESPRICE','NUMBOX','Sales Pricee','ITEMINPUTUI','ITMPNL_B','SALESPRICE',2,3)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain)  VALUES ('WAREHOUSE','ITEM','LOOKUPVEND','SEARCHBOX','Vendor','ITEMINPUTUI','ITMPNL_B','VENDORCODE','VENDORTXT',2,4,'APPDOMAIN.VENDOR')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','MAIN_EDITLISTVIEW','TABLE','Item List','ITEMLIST','ITEMLISTUI','ROOT',0,0)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','LV_ID','TABLETEXTCOLUMN','ID','ITEMLISTUI','MAIN_EDITLISTVIEW','ID',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','LV_ITEMID','TABLETEXTCOLUMN','Item ID','ITEMLISTUI','MAIN_EDITLISTVIEW','ITEMID',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','ITEM','LV_ITEMNAME','TABLETEXTCOLUMN','Item Name','ITEMLISTUI','MAIN_EDITLISTVIEW','NAME',3,1)

-- Functions
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_SAVE','SAVE','UIVIEW','ITEM_CREATE_VIEW','Save',0,'','AFTERSAVEACTION=GOTOVIEW#GOTOVIEWPATH=Items/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_BACK','NAVIGATE','UIVIEW','ITEM_CREATE_VIEW','Back to list',0,'ITEM_LISTVIEW','UIVIEW','Items/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_SAVE1','SAVE','UIVIEW','ITEM_EDIT_VIEW','Save',0,'','AFTERSAVEACTION=REFRESH')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_BACK1','NAVIGATE','UIVIEW','ITEM_EDIT_VIEW','Back to list',0,'ITEM_LISTVIEW','UIVIEW','Items/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_CREATE','CREATE','LISTINTERFACE','ITEMLISTUI','Create',0,'ITEM_CREATE_VIEW','UIVIEW','Items/Create')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_EDIT','EDIT','LISTINTERFACE','ITEMLISTUI','Edit',0,'ITEM_EDIT_VIEW','UIVIEW','Items/Edit/{id}')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_DELETE','DELETE','LISTINTERFACE','ITEMLISTUI','Delete',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_FILTER','FILTER','LISTINTERFACE','ITEMLISTUI','Filter',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','ITEM','ITEM_FUNC_PAGING','PAGING','LISTINTERFACE','ITEMLISTUI','Paging',0,'')


-- Application: Sales Order
-- Database
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','SALESORDER','ORDERNO','DATACOLUMN','ROOT','OrderNo','STRING','DEFVALUE=AUTO#DEFVALUE_START=1000#DEFVALUE_PREFIX=SO#DEFVALUE_SEED=100#UNIQUE=TRUE#MANDATORY=TRUE')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','ORDERDATE','DATACOLUMN','ROOT','OrderDate','DATETIME')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','CUSTID','DATACOLUMN','ROOT','CustomerId','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','CUSTNAME','DATACOLUMN','ROOT','CustomerName','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','DTORDLINE','DATATABLE','ROOT','wms_SalesLine','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','DTORDLINE_ITEMID','DATACOLUMN','DTORDLINE','ItemNo','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','DTORDLINE_ITEMNAME','DATACOLUMN','DTORDLINE','ItemName','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','DTORDLINE_QTY','DATACOLUMN','DTORDLINE','Qty','INTEGER')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','SALESORDER','DTORDLINE_ORDERNO','DATACOLUMN','DTORDLINE','OrderNo','STRING')

-- Views
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','SALESORDER','SO_LISTVIEW','UIVIEW','Sales Orders','SALESORDERLIST','SalesOrders/List',1,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','SALESORDER','SO_CREATE_VIEW','UIVIEW','Create Sales Order','','SalesOrders/Create',0,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','SALESORDER','SO_EDIT_VIEW','UIVIEW','Edit Sales Order','','SalesOrders/Edit/{id}',0,0)

-- Userinterface
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','SALESORDER','SO_INPUTUI','INPUTINTERFACE','SO_CREATE_VIEW','SALESORDER')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','SALESORDER','SO_INPUTUI','INPUTINTERFACE','SO_EDIT_VIEW','SALESORDER')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','SALESORDER','SO_ORDLINE_UI','LISTINTERFACE','SO_EDIT_VIEW','DTORDLINE')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','SALESORDER','SO_CREATE_ORDLINE_UI','INPUTINTERFACE','SO_EDIT_VIEW','DTORDLINE')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','SALESORDER','SO_EDIT_ORDLINE_UI','INPUTINTERFACE','SO_EDIT_VIEW','DTORDLINE')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','SALESORDER','SO_LISTUI','LISTINTERFACE','SO_LISTVIEW','SALESORDER')

-- UI Components
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','SALESORDER','SECT_CRORDLINE_HDR','SECTION','Create Order Line','CRORDLINE','SO_CREATE_ORDLINE_UI','ROOT',1,1,'COLLAPSIBLE=FALSE#STARTEXPANDED=FALSE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','CR_ORDLINE_PANEL','PANEL','','SO_CREATE_ORDLINE_UI','SECT_CRORDLINE_HDR',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain)  VALUES ('WAREHOUSE','SALESORDER','CR_TB_LINEITEM','SEARCHBOX','Item','SO_CREATE_ORDLINE_UI','CR_ORDLINE_PANEL','DTORDLINE_ITEMID','DTORDLINE_ITEMNAME',1,1,'APPDOMAIN.ITEM')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','CR_TB_LINEQTY','NUMBOX','Qty','SO_CREATE_ORDLINE_UI','CR_ORDLINE_PANEL','DTORDLINE_QTY',1,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','SALESORDER','SECT_ORDLINE_HDR','SECTION','Edit Order Line','EDORDLINE','SO_EDIT_ORDLINE_UI','ROOT',1,1,'COLLAPSIBLE=FALSE#STARTEXPANDED=FALSE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','ORDLINE_PANEL','PANEL','','SO_EDIT_ORDLINE_UI','SECT_ORDLINE_HDR',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain)  VALUES ('WAREHOUSE','SALESORDER','TB_LINEITEM','SEARCHBOX','Item','SO_EDIT_ORDLINE_UI','ORDLINE_PANEL','DTORDLINE_ITEMID','DTORDLINE_ITEMNAME',1,1,'APPDOMAIN.ITEM')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','TB_LINEQTY','NUMBOX','Qty','SO_EDIT_ORDLINE_UI','ORDLINE_PANEL','DTORDLINE_QTY',1,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','SALESORDER','SECT_HDR','SECTION','Sales Header','SO_INPUTUI','ROOT',1,1,'COLLAPSIBLE=FALSE#STARTEXPANDED=FALSE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','PANEL1','PANEL','','SO_INPUTUI','SECT_HDR',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','SALESORDER','TB_ORDERNO','TEXTBOX','Order No','SO_INPUTUI','PANEL1','ORDERNO',1,1,'READONLY=TRUE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','DP_ORDERDATE','DATEPICKER','Order Date','SO_INPUTUI','PANEL1','ORDERDATE',1,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain)  VALUES ('WAREHOUSE','SALESORDER','LOOKUP_CUSTOMER','SEARCHBOX','Customer','SO_INPUTUI','PANEL1','CUSTID','CUSTNAME',1,3,'APPDOMAIN.CUSTOMER')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','SALESORDER','MAIN_EDITLISTVIEW','TABLE','Sales Orders','SALESORDERLIST','SO_LISTUI','ROOT',0,0,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','LV_ID','TABLETEXTCOLUMN','ID','SO_LISTUI','MAIN_EDITLISTVIEW','ID',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','LF_ORDERID','TABLETEXTCOLUMN','Order No','SO_LISTUI','MAIN_EDITLISTVIEW','ORDERNO',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','LF_CUSTNAME','TABLETEXTCOLUMN','Customer','SO_LISTUI','MAIN_EDITLISTVIEW','CUSTNAME',3,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','SALESORDER','ORDERLINE_LISTVIEW','TABLE','Order Lines','ORDLINES','SO_ORDLINE_UI','ROOT',0,0,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','OL_ITEMID','TABLETEXTCOLUMN','Item','SO_ORDLINE_UI','ORDERLINE_LISTVIEW','DTORDLINE_ITEMID',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','OL_ITEMNAME','TABLETEXTCOLUMN','Name','SO_ORDLINE_UI','ORDERLINE_LISTVIEW','DTORDLINE_ITEMNAME',3,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','SALESORDER','OL_QTY','TABLETEXTCOLUMN','Qty','SO_ORDLINE_UI','ORDERLINE_LISTVIEW','DTORDLINE_QTY',4,1)

-- Functions
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_SAVE','SAVE','UIVIEW','SO_CREATE_VIEW','Save',0,'','AFTERSAVEACTION=GOTOVIEW#GOTOVIEWPATH=SalesOrders/Edit/{id}')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_BACK','NAVIGATE','UIVIEW','SO_CREATE_VIEW','Back to list',0,'SO_LISTVIEW','UIVIEW','SalesOrders/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_SAVE1','SAVE','UIVIEW','SO_EDIT_VIEW','Save',0,'','AFTERSAVEACTION=REFRESH')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_BACK1','NAVIGATE','UIVIEW','SO_EDIT_VIEW','Back to list',0,'SO_LISTVIEW','UIVIEW','SalesOrders/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_CREATE','CREATE','LISTINTERFACE','SO_LISTUI','Create',0,'SO_CREATE_VIEW','UIVIEW','SalesOrders/Create')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_EDIT','EDIT','LISTINTERFACE','SO_LISTUI','Edit',0,'SO_EDIT_VIEW','UIVIEW','SalesOrders/Edit/{id}')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_DELETE','DELETE','LISTINTERFACE','SO_LISTUI','Delete',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_FILTER','FILTER','LISTINTERFACE','SO_LISTUI','Filter',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','SO_FUNC_PAGING','PAGING','LISTINTERFACE','SO_LISTUI','Paging',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','OL_FUNC_CREATE','CREATE','LISTINTERFACE','SO_ORDLINE_UI','Create',1,'SO_CREATE_ORDLINE_UI','INPUTINTERFACE','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','OL_FUNC_EDIT','EDIT','LISTINTERFACE','SO_ORDLINE_UI','Edit',1,'SO_EDIT_ORDLINE_UI','INPUTINTERFACE','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','OL_FUNC_DELETE','DELETE','LISTINTERFACE','SO_ORDLINE_UI','Delete',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','OL_FUNC_FILTER','FILTER','LISTINTERFACE','SO_ORDLINE_UI','Filter',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','SALESORDER','OL_FUNC_PAGING','PAGING','LISTINTERFACE','SO_ORDLINE_UI','Paging',0,'')


-- Application: Vendor
-- Database
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','VENDOR','VENDORID','DATACOLUMN','ROOT','VendorId','STRING','DEFVALUE=AUTO#DEFVALUE_START=1000#DEFVALUE_PREFIX=VEND#DEFVALUE_SEED=100#UNIQUE=TRUE#MANDATORY=TRUE')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType)  VALUES ('WAREHOUSE','VENDOR','VENDORNAME','DATACOLUMN','ROOT','VendorName','STRING')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Description,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','VENDOR','H7314920PMKGB8ZHEUTU','DATACOLUMN','','ROOT','IsValidated','STRING','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Description,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','VENDOR','9YW15546PMBPNB2BKQHW','DATACOLUMN','','ROOT','PrioValue','TEXT','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Description,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','VENDOR','T3D15546PMR3OMIUSBWN','DATACOLUMN','','ROOT','PrioText','TEXT','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Description,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','VENDOR','WXR15630PMDJCUCIKCNH','DATACOLUMN','','ROOT','AttrId','TEXT','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Description,ParentMetaCode,DbName,DataType,Properties)  VALUES ('WAREHOUSE','VENDOR','IQ615630PMPKUOSPUYPX','DATACOLUMN','','ROOT','AttrText','TEXT','')

-- Views
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','VENDOR','VEND_LISTVIEW','UIVIEW','Vendor List','VENDORLIST','Vendors/List',1,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','VENDOR','VEND_CREATE_VIEW','UIVIEW','Create Vendor','','Vendors/Create',0,0)
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic)  VALUES ('WAREHOUSE','VENDOR','VEND_EDIT_VIEW','UIVIEW','Edit Vendor','','Vendors/Edit/{id}',0,0)

-- Userinterface
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','VENDOR','VEND_INPUTUI','INPUTINTERFACE','VEND_CREATE_VIEW','VENDOR')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','VENDOR','VEND_INPUTUI','INPUTINTERFACE','VEND_EDIT_VIEW','VENDOR')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('WAREHOUSE','VENDOR','VEND_LISTUI','LISTINTERFACE','VEND_LISTVIEW','VENDOR')

-- UI Components
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','VENDOR','MAINSECTION','SECTION','','VEND_INPUTUI','ROOT',1,1,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','VENDOR','PNL1','PANEL','Basics','UI_LOC_Q5W20526PMYEUPIGESBE','VEND_INPUTUI','MAINSECTION',1,1,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataTableMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain,Properties,RawHTML)  VALUES ('WAREHOUSE','VENDOR','TB_VENDID','TEXTBOX','Vendor ID','VEND_INPUTUI','PNL1','VENDOR','VENDORID','',1,1,'','READONLY=TRUE','')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataTableMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain,Properties,RawHTML)  VALUES ('WAREHOUSE','VENDOR','TB_VENDNAME','TEXTBOX','Vendor Name','VEND_INPUTUI','PNL1','VENDOR','VENDORNAME','',1,2,'','','')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','VENDOR','RKS14920PMFINERTUGP5','SECTION','','VEND_INPUTUI','ROOT',1,2,'STARTEXPANDED=TRUE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('WAREHOUSE','VENDOR','ERH14920PMHRGKHSEWOY','PANEL','Classification','UI_LOC_1N220526PMWWWRFWKABG','VEND_INPUTUI','RKS14920PMFINERTUGP5',1,1,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataTableMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain,Properties,RawHTML)  VALUES ('WAREHOUSE','VENDOR','NC14920PMLBFEVZECRDO','YESNOUNKNOWN','Is Validated','VEND_INPUTUI','ERH14920PMHRGKHSEWOY','VENDOR','H7314920PMKGB8ZHEUTU','',1,1,'','','')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataTableMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain,Properties,RawHTML)  VALUES ('WAREHOUSE','VENDOR','PLX15546PM9JYPUGU6QL','RADIOLIST','Priority','VEND_INPUTUI','ERH14920PMHRGKHSEWOY','VENDOR','9YW15546PMBPNB2BKQHW','T3D15546PMR3OMIUSBWN',1,2,'VALUEDOMAIN.VENDORPRIO','','')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataTableMetaCode,DataColumn1MetaCode,DataColumn2MetaCode,ColumnOrder,RowOrder,Domain,Properties,RawHTML)  VALUES ('WAREHOUSE','VENDOR','KZT15630PMA9YI7K1WJV','CHECKLIST','Attributes','VEND_INPUTUI','ERH14920PMHRGKHSEWOY','VENDOR','WXR15630PMDJCUCIKCNH','IQ615630PMPKUOSPUYPX',1,3,'VALUEDOMAIN.VENDORATTRIBUTES','ORIENTATION=VERTICAL','')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','VENDOR','MAIN_EDITLISTVIEW','TABLE','Vendor List','','VEND_LISTUI','ROOT',0,0)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','VENDOR','LV_ID','TABLETEXTCOLUMN','ID','VEND_LISTUI','MAIN_EDITLISTVIEW','ID',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','VENDOR','LV_VENDID','TABLETEXTCOLUMN','Vendor ID','VEND_LISTUI','MAIN_EDITLISTVIEW','VENDORID',2,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('WAREHOUSE','VENDOR','LV_VENDNAME','TABLETEXTCOLUMN','Vendor Name','VEND_LISTUI','MAIN_EDITLISTVIEW','VENDORNAME',3,1)

-- Functions
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_SAVE','SAVE','UIVIEW','VEND_CREATE_VIEW','Save',0,'','AFTERSAVEACTION=GOTOVIEW#GOTOVIEWPATH=Vendors/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_BACK','NAVIGATE','UIVIEW','VEND_CREATE_VIEW','Back to list',0,'VEND_LISTVIEW','UIVIEW','Vendors/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_SAVE1','SAVE','UIVIEW','VEND_EDIT_VIEW','Save',0,'','AFTERSAVEACTION=REFRESH')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_BACK1','NAVIGATE','UIVIEW','VEND_EDIT_VIEW','Back to list',0,'VEND_LISTVIEW','UIVIEW','Vendors/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_CREATE','CREATE','LISTINTERFACE','VEND_LISTUI','Create',0,'VEND_CREATE_VIEW','UIVIEW','Vendors/Create')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_EDIT','EDIT','LISTINTERFACE','VEND_LISTUI','Edit',0,'VEND_EDIT_VIEW','UIVIEW','Vendors/Edit/{id}')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_DELETE','DELETE','LISTINTERFACE','VEND_LISTUI','Delete',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_FILTER','FILTER','LISTINTERFACE','VEND_LISTUI','Filter',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('WAREHOUSE','VENDOR','VEND_FUNC_PAGING','PAGING','LISTINTERFACE','VEND_LISTUI','Paging',0,'')


-- Application: The blog
-- Database
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('BLOG','BLOGAPP','POSTHEADER','DATACOLUMN','ROOT','ArticleHeader','STRING','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('BLOG','BLOGAPP','POSTTEXT','DATACOLUMN','ROOT','ArticleText','TEXT','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('BLOG','BLOGAPP','POSTIMAGE','DATACOLUMN','ROOT','ArticleImage','STRING','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('BLOG','BLOGAPP','POSTCOMMENTS','DATATABLE','ROOT','blog_ArticleComments','STRING','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('BLOG','BLOGAPP','COMMENTHEADER','DATACOLUMN','POSTCOMMENTS','CommentLabel','STRING','')
INSERT INTO sysmodel_DatabaseItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,DbName,DataType,Properties)  VALUES ('BLOG','BLOGAPP','COMMENTTEXT','DATACOLUMN','POSTCOMMENTS','CommentText','TEXT','')

-- Views
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,FilePath,IsPrimary,IsPublic,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_LISTVIEW','UIVIEW','Blog Posts','','/Blog/List','Views/Application/Blog/blogview.cshtml',1,0,'')
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,FilePath,IsPrimary,IsPublic,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_CREATE_VIEW','UIVIEW','Create Blog Post','','/Blog/Create','Views/Application/Blog/blogview.cshtml',0,0,'')
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,FilePath,IsPrimary,IsPublic,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_EDIT_VIEW','UIVIEW','Edit Blog Post','','/Blog/Edit/{id}','Views/Application/Blog/blogview.cshtml',0,0,'')
INSERT INTO sysmodel_ViewItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,Path,IsPrimary,IsPublic,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_PUBLIC_VIEW','UIVIEW','The Intwenty Blog','','Blog/Index',0,1,'')

-- Userinterface
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('BLOG','BLOGAPP','BLOG_INPUTUI','INPUTINTERFACE','BLOG_CREATE_VIEW','BLOGAPP')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('BLOG','BLOGAPP','BLOG_INPUTUI','INPUTINTERFACE','BLOG_EDIT_VIEW','BLOGAPP')
INSERT INTO sysmodel_UserInterfaceItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ViewMetaCode,DataTableMetaCode)  VALUES ('BLOG','BLOGAPP','BLOG_LISTUI','LISTINTERFACE','BLOG_LISTVIEW','BLOGAPP')

-- UI Components
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('BLOG','BLOGAPP','MAINSECTION','SECTION','','BLOG_INPUTUI','ROOT',1,1,'COLLAPSIBLE=FALSE#STARTEXPANDED=FALSE')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('BLOG','BLOGAPP','PNL1','PANEL','','BLOG_INPUTUI','MAINSECTION',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('BLOG','BLOGAPP','TB_HEADER','TEXTBOX','Article Header','BLOG_INPUTUI','PNL1','POSTHEADER',1,1,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('BLOG','BLOGAPP','TB_TEXT','TEXTAREA','Article Text','BLOG_INPUTUI','PNL1','POSTTEXT',1,2)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('BLOG','BLOGAPP','PNL2','PANEL','','BLOG_INPUTUI','MAINSECTION',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder,Properties)  VALUES ('BLOG','BLOGAPP','IMGBOX_ARTIMAGE','IMAGEBOX','Image','BLOG_INPUTUI','PNL2','POSTIMAGE',1,1,'')
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,TitleLocalizationKey,UserInterfaceMetaCode,ParentMetaCode,ColumnOrder,RowOrder)  VALUES ('BLOG','BLOGAPP','MAIN_EDITLISTVIEW','TABLE','Articles','','BLOG_LISTUI','ROOT',0,0)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('BLOG','BLOGAPP','ELV_ID','TABLETEXTCOLUMN','ID','BLOG_LISTUI','MAIN_EDITLISTVIEW','ID',1,1)
INSERT INTO sysmodel_UserInterfaceStructureItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,Title,UserInterfaceMetaCode,ParentMetaCode,DataColumn1MetaCode,ColumnOrder,RowOrder)  VALUES ('BLOG','BLOGAPP','ELV_POSTHEADER','TABLETEXTCOLUMN','Article Header','BLOG_LISTUI','MAIN_EDITLISTVIEW','POSTHEADER',2,1)

-- Functions
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_SAVE','SAVE','UIVIEW','BLOG_CREATE_VIEW','Save',0,'','AFTERSAVEACTION=GOTOVIEW#GOTOVIEWPATH=Blog/List')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_BACK','NAVIGATE','UIVIEW','BLOG_CREATE_VIEW','Back to list',0,'BLOG_LISTVIEW','UIVIEW','/Blog/List','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_SAVE1','SAVE','UIVIEW','BLOG_EDIT_VIEW','Save',0,'','AFTERSAVEACTION=REFRESH')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath,Properties)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_BACK1','NAVIGATE','UIVIEW','BLOG_EDIT_VIEW','Back to list',0,'BLOG_LISTVIEW','UIVIEW','/Blog/List','')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_CREATE','CREATE','LISTINTERFACE','BLOG_LISTUI','Create',0,'BLOG_CREATE_VIEW','UIVIEW','Blog/Create')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionMetaCode,ActionMetaType,ActionPath)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_EDIT','EDIT','LISTINTERFACE','BLOG_LISTUI','Edit',0,'BLOG_EDIT_VIEW','UIVIEW','Blog/Edit/{id}')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_DELETE','DELETE','LISTINTERFACE','BLOG_LISTUI','Delete',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_FILTER','FILTER','LISTINTERFACE','BLOG_LISTUI','Filter',0,'')
INSERT INTO sysmodel_FunctionItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,OwnerMetaType,OwnerMetaCode,Title,IsModalAction,ActionPath)  VALUES ('BLOG','BLOGAPP','BLOG_FUNC_PAGING','PAGING','LISTINTERFACE','BLOG_LISTUI','Paging',0,'')

-- Domains
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('ITEMCATEGORY','PROD','Products')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('ITEMCATEGORY','SERV','Services')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('CUSTOMERTAGS','1','Tag 1')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('CUSTOMERTAGS','2','Tag 2')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('CUSTOMERTAGS','3','Tag 3')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORPRIO','P3','Prio 3')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORPRIO','P1','Prio 1')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORPRIO','P2','Prio 2')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORATTRIBUTES','400','Low Quality')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORATTRIBUTES','300','High Quality')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORATTRIBUTES','200','Slow')
INSERT INTO sysmodel_ValueDomainItem (DomainName,Code,Value)  VALUES ('VENDORATTRIBUTES','100','Trusted')

-- Endpoints
INSERT INTO sysmodel_EndpointItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,Title,Path,Description,DataMetaCode,OrderNo)  VALUES ('WAREHOUSE','CUSTOMER','EP_CUSTOMER_GETLATEST','TABLEGET','ROOT','Get customer','MyAPI/Customer','Get latest version of a customer by id','CUSTOMER',0)
INSERT INTO sysmodel_EndpointItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,Title,Path,Description,DataMetaCode,OrderNo)  VALUES ('WAREHOUSE','CUSTOMER','EP_CUSTOMER_GETALL','TABLELIST','ROOT','Get all customers','MyAPI/Customers','Get all customers in the database','CUSTOMER',0)
INSERT INTO sysmodel_EndpointItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,Title,Path,Description,DataMetaCode,OrderNo)  VALUES ('WAREHOUSE','CUSTOMER','EP_CUSTOMER_SAVE','TABLESAVE','ROOT','Save customer','MyAPI/Customer/Save','Create or update customer','CUSTOMER',0)
INSERT INTO sysmodel_EndpointItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,Title,Path,Description,DataMetaCode,OrderNo)  VALUES ('WAREHOUSE','','EP_CUST_1','CUSTOMPOST','ROOT','Post Anything','MyAPI/PostAnyThing','This endpoint must be implemented in a custom controller','',0)
INSERT INTO sysmodel_EndpointItem (SystemMetaCode,AppMetaCode,MetaCode,MetaType,ParentMetaCode,Title,Path,Description,DataMetaCode,OrderNo)  VALUES ('WAREHOUSE','','EP_AUTH','CUSTOMPOST','ROOT','Authenticate with a product','MyAPI/Authenticate','Authenticates a user','',0)
